----------------------------------------//db.properties//-------------------------------------------------
#db.host=ttltweb_juicy-db_1
#db.port=3306
#db.username=root
#db.password=root
#db.dbName=juicy_db

db.host=localhost
db.port=3306
db.username=root
db.password=Hockun001$
db.dbName=juicy_db
db.pool.maximumPoolSize=20
db.pool.minimumIdle=5
db.pool.connectionTimeout=30000
db.pool.idleTimeout=600000
db.pool.maxLifetime=1800000
--------------------------------------------//gg.properties//----------------------------------------------
//mailTri
google.client.id=428843252318-uhjd24qp528ml144m0llip2721h8ite9.apps.googleusercontent.com
google.client.secret=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
google.redirect.uri=http://localhost:8080/login-google

//mailWeb
#google.client.id=577413463215-l9itu115km2s0hivomg7b9lo77rrjjc0.apps.googleusercontent.com
#google.client.secret=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
#google.redirect.uri=https://nbhoc0605.id.vn/login-google
------------------------------------------//mail.properties//-----------------------------------------------
mail.from=juicyxinchao@gmail.com
mail.password=hudywjeeatkfivvw


# Thông tin tài kho?n m?c ??nh (cho trang liên h?)
mail.to.default=luonghoaisangvn@gmail.com

# C?u hình SMTP Server
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true

mail.smtp.starttls.required=true
mail.smtp.ssl.protocols=TLSv1.2 TLSv1.3
------------------------------------------//vnp.properties//--------------------------------------------------
vnp.tmn_code=V0ERG9EF
vnp.hash_secret=S8HNSC9BI03BI1L4Z1553WH6BEM415J0
vnp.pay_url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnp.return_url=https://nbhoc0605.id.vn/vnpay_return
------------------------------------------//ghn.properties//--------------------------------------------------
ghn.shop.id=200521
ghn.token.api=e2aa70bf-5da0-11f1-a973-aee5264794df