----------------------------------------//db.properties//-------------------------------------------------
db.host=ttltweb_juicy-db_1
db.port=3306
db.username=root
db.password=root
db.dbName=juicy_db

#db.host=localhost
#db.port=3306
#db.username=root
#db.password=Hockun001$
#db.dbName=juicy_db
--------------------------------------------//gg.properties//----------------------------------------------
google.client.id= 428843252318-uhjd24qp528ml144m0llip2721h8ite9.apps.googleusercontent.com
google.client.secret=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
google.redirect.uri=http://localhost:8080/login-google

------------------------------------------//mail.properties//-----------------------------------------------
# Thông tin tài kho?n g?i
//mail.from=weebooguy@gmail.com
//mail.password=jtrw hgae qbqa mhjm

mail.from=juicyxinchao@gmail.com
mail.password=h u d y w j e e a t k f i v v w


# Thông tin tài kho?n m?c ??nh (cho trang liên h?)
mail.to.default=luonghoaisangvn@gmail.com

# C?u hình SMTP Server
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true

------------------------------------------//vnp.properties//--------------------------------------------------
vnp.tmn_code=V0ERG9EF
vnp.hash_secret=S8HNSC9BI03BI1L4Z1553WH6BEM415J0
vnp.pay_url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnp.return_url=https://numbing-sterically-anitra.ngrok-free.dev/vnpay-return